# Develop stage databases mysql.
# -----------------------------------------------
version: '3.7'

volumes:
  mysql_data:

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.33
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: local_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    logging:
      driver: none
  web:
    build:
      context: .
      dockerfile: image/web.dockerfile
    ports:
      - "8080:8080"
    container_name: web
